FROM gradle:7.5.1-jdk17 AS build

WORKDIR /app

COPY . .

RUN gradle build

FROM openjdk:17-jdk-slim

COPY --from=build /app/build/libs/*.jar /app/service.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/service.jar"]
