version: "3.7"
services:
  minio-s3:
    image: minio/minio:latest
    command: minio server /var/lib/minio/data --console-address ":9001"
    secrets:
      - minio_root_user
      - minio_root_password
    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/minio_root_user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_root_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/var/lib/minio/data
    networks:
      - go_networks
    restart: always
secrets:
  minio_root_user:
    file: ./secrets/minio_root_user.txt
  minio_root_password:
    file: ./secrets/minio_root_password.txt
volumes:
  storage:
networks:
  go_networks:
