FROM node:21.5.0 AS build

WORKDIR /app

COPY ../frontend/package*.json ./

RUN npm install

COPY ../frontend ./

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY ../deploy/frontend-nginx.conf /etc/nginx/sites-enabled/frontend-nginx

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]