FROM node:21.5.0 AS build


WORKDIR /app

# Copy the package files from the frontend directory
COPY ../frontend/package*.json ./

RUN npm install

# Copy the rest of the frontend files
COPY ../frontend ./

RUN npm run build

FROM nginx:alpine

# Copy the build output to the Nginx html directory
COPY --from=build /app/dist /usr/share/nginx/html

# Copy a custom Nginx configuration file
COPY frontend-nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]