FROM gradle:7.6.0-jdk17 AS builder

WORKDIR /home/gradle/project

COPY --chown=gradle:gradle ../.. .

RUN gradle build --no-daemon

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=builder /home/gradle/project/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
