FROM node:21.5.0-alpine AS build

WORKDIR /app

# Copy the package files from the frontend directory
COPY ../frontend/package*.json ./

RUN npm install

# Copy the rest of the frontend files
COPY ../frontend ./

RUN npm run build

FROM nginx:alpine

# Copy the build output from the previous stage
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80