version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: deploy/Dockerfile-backend
    ports:
      - "${BACKEND_PORT}:8080"
    secrets:
      - app_vault_addr
      - app_vault_token
    environment:
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      APP_VAULT_ADDR: /run/secrets/app_vault_addr
      APP_VAULT_TOKEN: /run/secrets/app_vault_token
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ../
      dockerfile: deploy/Dockerfile-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - app-network
    restart: always

  minio-s3:
    image: minio/minio:latest
    command: minio server /var/lib/minio/data --console-address ":${MINIO_UI_PORT}"
    secrets:
      - minio_root_user
      - minio_root_password
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
    ports:
      - "${MINIO_CONNECTION_PORT}:9000"
      - "${MINIO_UI_PORT}:9001"
    volumes:
      - storage:/var/lib/minio/data
    networks:
      - app-network
    restart: always

secrets:
  minio_root_user:
    file: ./secrets/minio_root_user.txt
  minio_root_password:
    file: ./secrets/minio_root_password.txt
  app_vault_addr:
    file: ./secrets/app_vault_addr.txt
  app_vault_token:
    file: ./secrets/app_vault_token.txt

volumes:
  storage:

networks:
  app-network: