version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile-backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      APP_VAULT_ADDR: ${APP_VAULT_ADDR}
      APP_VAULT_TOKEN: ${APP_VAULT_TOKEN}
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - app-network
    restart: always

  minio-s3:
    image: minio/minio:latest
    command: minio server /var/lib/minio/data --console-address ":${MINIO_UI_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_CONNECTION_PORT}:9000"
      - "${MINIO_UI_PORT}:9001"
    volumes:
      - storage:/var/lib/minio/data
    networks:
      - app-network
    restart: always

volumes:
  storage:

networks:
  app-network: